"""initial schema

Revision ID: 24bcfef840fe
Revises:
Create Date: 2026-08-25 18:22:34.709667

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "24bcfef840fe"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Required by CITEXT columns (users.email, newsletter_subscribers.email).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bikes",
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("frame_number", sa.Text(), nullable=False),
        sa.Column("brand", sa.String(length=255), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=True),
        sa.Column("model_year", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "city", "trekking", "mtb", "road", "kids", "ebike", name="bike_category"
            ),
            nullable=False,
        ),
        sa.Column("frame_size", sa.String(length=50), nullable=True),
        sa.Column("wheel_size", sa.String(length=50), nullable=True),
        sa.Column(
            "condition_grade",
            sa.Enum("A", "B", "C", name="condition_grade"),
            nullable=False,
        ),
        sa.Column("price_cents", sa.Integer(), nullable=False),
        sa.Column("old_price_cents", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "work_done",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "available",
                "reserved",
                "sold",
                "withdrawn",
                name="bike_status",
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "photos",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_index(op.f("ix_bikes_status"), "bikes", ["status"], unique=False)
    op.create_table(
        "email_log",
        sa.Column("to_email", sa.String(length=255), nullable=False),
        sa.Column("template", sa.String(length=100), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.Enum("sent", "failed", name="email_status"), nullable=False
        ),
        sa.Column("provider_id", sa.String(length=255), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_log_to_email"), "email_log", ["to_email"], unique=False
    )
    op.create_table(
        "newsletter_subscribers",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("confirm_token_hash", sa.String(length=64), nullable=True),
        sa.Column("unsubscribe_token_hash", sa.String(length=64), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unsubscribed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_newsletter_subscribers_confirm_token_hash"),
        "newsletter_subscribers",
        ["confirm_token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_newsletter_subscribers_unsubscribe_token_hash"),
        "newsletter_subscribers",
        ["unsubscribe_token_hash"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("google_sub", sa.String(length=255), nullable=True),
        sa.Column(
            "role", sa.Enum("customer", "admin", name="user_role"), nullable=False
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("marketing_opt_in", sa.Boolean(), nullable=False),
        sa.Column("marketing_opt_in_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_sub"),
    )
    op.create_table(
        "workshops",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("contact_name", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", sa.Uuid(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_tokens_token_hash"),
        "refresh_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_tokens_user_id"), "refresh_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "reservations",
        sa.Column("bike_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "expired", "cancelled", "converted", name="reservation_status"
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["bike_id"], ["bikes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reservations_bike_id"), "reservations", ["bike_id"], unique=False
    )
    op.create_index(
        op.f("ix_reservations_user_id"), "reservations", ["user_id"], unique=False
    )
    op.create_index(
        "uq_reservation_active_bike",
        "reservations",
        ["bike_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_index(
        "uq_reservation_active_user",
        "reservations",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "service_records",
        sa.Column("bike_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("intake", "final", name="service_record_kind"),
            nullable=False,
        ),
        sa.Column("checklist", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("performed_by", sa.Text(), nullable=False),
        sa.Column("performed_at", sa.Date(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["bike_id"], ["bikes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bike_id", "kind", name="uq_service_record_bike_kind"),
    )
    op.create_index(
        op.f("ix_service_records_bike_id"), "service_records", ["bike_id"], unique=False
    )
    op.create_index(
        op.f("ix_service_records_created_by"),
        "service_records",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_service_records_workshop_id"),
        "service_records",
        ["workshop_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(length=32), nullable=False),
        sa.Column("bike_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "confirmed", "completed", "cancelled", name="order_status"
            ),
            nullable=False,
        ),
        sa.Column(
            "repair_tier",
            sa.Enum("basic", "quality", "premium", name="repair_tier"),
            nullable=False,
        ),
        sa.Column("bike_price_cents", sa.Integer(), nullable=False),
        sa.Column("tier_price_cents", sa.Integer(), nullable=False),
        sa.Column("total_cents", sa.Integer(), nullable=False),
        sa.Column(
            "billing_type",
            sa.Enum("individual", "company", name="billing_type"),
            nullable=False,
        ),
        sa.Column("billing_name", sa.String(length=255), nullable=False),
        sa.Column("billing_email", sa.String(length=255), nullable=False),
        sa.Column("billing_phone", sa.String(length=50), nullable=False),
        sa.Column("billing_street", sa.Text(), nullable=False),
        sa.Column("billing_city", sa.String(length=255), nullable=False),
        sa.Column("billing_county", sa.String(length=64), nullable=False),
        sa.Column("billing_postal_code", sa.String(length=16), nullable=False),
        sa.Column(
            "billing_country", sa.String(length=2), server_default="RO", nullable=False
        ),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("company_cui", sa.String(length=16), nullable=True),
        sa.Column("company_reg_com", sa.String(length=32), nullable=True),
        sa.Column(
            "delivery_method",
            sa.Enum("pickup", "courier", name="delivery_method"),
            nullable=False,
        ),
        sa.Column("delivery_name", sa.String(length=255), nullable=True),
        sa.Column("delivery_phone", sa.String(length=50), nullable=True),
        sa.Column("delivery_street", sa.Text(), nullable=True),
        sa.Column("delivery_city", sa.String(length=255), nullable=True),
        sa.Column("delivery_county", sa.String(length=64), nullable=True),
        sa.Column("delivery_postal_code", sa.String(length=16), nullable=True),
        sa.Column("delivery_country", sa.String(length=2), nullable=True),
        sa.Column("terms_version", sa.String(length=32), nullable=False),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("terms_accepted_ip", postgresql.INET(), nullable=False),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column("admin_note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bike_id"],
            ["bikes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_number"),
    )
    op.create_index(op.f("ix_orders_bike_id"), "orders", ["bike_id"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Sequence backing orders.order_number (e.g. "SC-2026-000123").
    op.execute("CREATE SEQUENCE IF NOT EXISTS order_number_seq")


def downgrade() -> None:
    op.execute("DROP SEQUENCE IF EXISTS order_number_seq")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_bike_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_service_records_workshop_id"), table_name="service_records")
    op.drop_index(op.f("ix_service_records_created_by"), table_name="service_records")
    op.drop_index(op.f("ix_service_records_bike_id"), table_name="service_records")
    op.drop_table("service_records")
    op.drop_index(
        "uq_reservation_active_user",
        table_name="reservations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(
        "uq_reservation_active_bike",
        table_name="reservations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_reservations_user_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_bike_id"), table_name="reservations")
    op.drop_table("reservations")
    op.drop_index(op.f("ix_refresh_tokens_user_id"), table_name="refresh_tokens")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("workshops")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_newsletter_subscribers_unsubscribe_token_hash"),
        table_name="newsletter_subscribers",
    )
    op.drop_index(
        op.f("ix_newsletter_subscribers_confirm_token_hash"),
        table_name="newsletter_subscribers",
    )
    op.drop_table("newsletter_subscribers")
    op.drop_index(op.f("ix_email_log_to_email"), table_name="email_log")
    op.drop_table("email_log")
    op.drop_index(op.f("ix_bikes_status"), table_name="bikes")
    op.drop_table("bikes")
    # ### end Alembic commands ###

    # Drop the native enum types the tables above created (drop_table does not).
    for enum_name in (
        "order_status",
        "repair_tier",
        "billing_type",
        "delivery_method",
        "reservation_status",
        "service_record_kind",
        "bike_category",
        "condition_grade",
        "bike_status",
        "user_role",
        "email_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute("DROP EXTENSION IF EXISTS citext")
